create table topicos(

    id                  bigint       not null GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    titulo              varchar(100) not null,
    mensaje             varchar(255) not null,
    fecha_creacion      timestamp    not null,
    estado              boolean      not null,
    usuario_id          bigint       not null,
    curso               bigint       not null,

    primary key (id),
    constraint fk_topicos_usuario_id foreign key (usuario_id) references usuarios(id),
    constraint fk_topicos_curso_id foreign key (curso_id) references cursos(id)

    );