create table usuarios(

                         id                  bigint       not null GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
                         nombre              varchar(100) not null,
                         email               varchar(255) not null unique,
                         contrasenia         varchar(255) not null,
                         activo              boolean,

                         primary key (id)

);

create table cursos(

                       id                  bigint       not null GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
                       nombre              varchar(100) not null,
                       categoria           varchar(255) not null,
                       activo              boolean,

                       primary key (id)

);

create table topicos(

                        id                  bigint       not null GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
                        titulo              varchar(100) not null,
                        mensaje             varchar(255) not null,
                        fecha_creacion      timestamp    not null,
                        estado              boolean      not null,
                        usuario_id          bigint       not null,
                        curso_id               bigint       not null,

                        primary key (id),
                        constraint fk_topicos_usuario_id foreign key (usuario_id) references usuarios(id),
                        constraint fk_topicos_curso_id foreign key (curso_id) references cursos(id)

);

create table respuestas(

                           id                  bigint       not null GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
                           topico_id              bigint       not null,
                           mensaje             varchar(255) not null,
                           fecha_creacion      timestamp    not null,
                           usuario_id          bigint       not null,
                           solucionado         boolean      not null,

                           primary key (id),
                           constraint fk_respuestas_usuario_id foreign key (usuario_id) references usuarios(id),
                           constraint fk_respuestas_topico_id foreign key (topico_id) references topicos(id)

);